### ISSUE TITLE
Sample Unity Project

### ISSUE THREAD

**Issue by BHUVAN007** [ebadier/Motive-Tools#1]
Hi! I am quite new to both unity and Motive. I tried to read rigid body data without using dll files and it worked fine for one rigid body and was quite not so accurate for multiple rigid bodies. I tried to use unity 3d samples from NatNetSDK and used your project for data streaming. But I couldn't get rigid body data to my game object. Is there a simple sample project you implemented to check data streaming?

**Comment by ebadier** [comment]
Hi BHUVAN007,

I'm not sure to understand very well your problem.

Typically, to be able to stream data from Motive to Unity3D, you should do this:
1) Open a Motive project contains at least 1 Rigid Body and/or 1 Skeleton
2) In Motive Set the DataStreaming options as https://github.com/ebadier/Motive-Tools/blob/master/MotiveUnityServer/bin/x64/Release/MotiveDataStreamingConfig.png
3) Launch the UnityServer using https://github.com/ebadier/Motive-Tools/blob/master/MotiveUnityServer/bin/x64/Release/MotiveUnityServer.bat
4) Launch the UnityClient https://github.com/ebadier/Motive-UnityClient/blob/master/MotiveTest.unity

What version of Motive are you using ? If you use Motive 1.8.0 or above, it should works fine.

Hope this helps.

**Comment by BHUVAN007** [comment]
Thanks!

I was asking about the last step you mentioned. I couldn't launch the unity client. For some reason I couldn't make it work.
